# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

plugins:
   - multiple-languages

languages: ["en", "ka"]

exclude_from_localizations: ["javascript", "images", "css", "CNAME"]

defaultLang: en

languageNames:
  ka: ქართული
  en: English


# Setup
title:            David Sichinava
tagline:          'A Jekyll theme'
description:      'Research Director at CRRC-Georgia | Assistant Professor at Tbilisi State University</a>.'
url:              http://sichinava.ge
baseurl:          /

author:
  name:           'David Sichinava'
  url:            https://twitter.com/davidsichinava

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/davidsichinava
