baseURL = ""
languageCode = "en-US"
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"
canonifyURLs = "true"
title = "David Sichinava"
theme = "anubis"

[languages]
  [languages.en]
    title = "Pollster.ge"
    contentDir = "content/english"
    languageName = "English"
    weight = 1

[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1


[languages.ka]
    title = "Pollster.ge"
    contentDir = "content/kartuli"
    languageName = "ქართული"
    weight = 2
	
[[languages.ka.menu.main]]
  identifier = "about"
  name = "ჩემს შესახებ"
  url = "/about/"
  weight = 1

[params]
    customCss = ["css/pollster.css"]